version: 2

models:
  - name: int_localbike__order_items
    description: '{{ doc("int_localbike__order_items") }}'
    columns:
      - name: pk_order
        description: "Primary Key"
        tests:
          - unique
          - not_null

  - name: int_localbike__stocks
    description: '{{ doc("int_localbike__stocks") }}'
    columns:
      - name: product_name
        description: The nzme of the product
