version: 2

models:
  - name: int_localbike__order_items
    description: "Intermediate model in order to prepare mrt_model"
    columns:
      - name: pk_order
        description: "Primary Key"
        tests:
          - unique
          - not_null

  - name: int_localbike__stocks
    description: "Intermediate model in order to prepare mrt_model"
    columns:
      - name: product_name
        description: The nzme of the product
